#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
if ! [ -f ./buildenv ]; then
	echo "Need to source from the buildenv directory" >&2
	return 0
fi

export ZOPEN_ROOT="${PWD}"
export ZOPEN_TYPE="TARBALL"
export ZOPEN_TARBALL_URL="https://ftp.gnu.org/gnu/libtool/libtool-2.4.tar.gz"
export ZOPEN_TARBALL_DEPS="curl gzip make m4 perl autoconf"

export ZOPEN_GIT_URL="https://github.com/autotools-mirror/libtool.git"
export ZOPEN_GIT_DEPS="git make m4 perl autoconf automake help2man makeinfo xz"

export ZOPEN_EXTRA_CFLAGS=""
export ZOPEN_EXTRA_LDFLAGS=""

if [ "${ZOPEN_TYPE}x" = "TARBALLx" ]; then
	export ZOPEN_BOOTSTRAP=skip
fi
